### ISSUE TITLE
关于技术选型，各位有想法请评论，谢谢

### ISSUE THREAD

**Issue by hstarorg** [chengdujs/cd-it-job#1]
现提供一种方案：

前端：Vue2+webpack+WeUI

后端：Express +MongoDB

**Comment by jikeytang** [comment]
非常赞成楼上的技术选型，如果非要有个备选的话，我提供一种方案，供参考：
前端：React+webpack+WeUI,
后端：PHP+mysql
使用React的理由是：虚拟DOM，JSX。
推荐PHP的理由是：Nodejs虽然语言统一，但是空间价格贵且难选，相对PHP来说更价低易选择。

**Comment by hstarorg** [comment]
React 和 Vue2 相比较，非常类似了，只是Vue2上手更快一些。

后端的话，如果考虑到吸引前端人群的话，可能更多的倾向于前端技术栈。作为前后端分离，后端也只提供API。

所以运行时可能node更合适一些。至于数据库，还可以再斟酌下~

**Comment by hstarorg** [comment]
经过论证，第一个版本相关方案如下：

前端：Vue2 + webpack + WeUI
后端： Node（Express）+ MongoDB

开发模式：前后端分离，SPA。
开源模式：除核心开发者外，其他贡献者通过Fork项目，提PR来贡献代码。

**Comment by yibuyisheng** [comment]
项目在进行吗？

**Comment by hstarorg** [comment]
@yibuyisheng 是的，api项目已经提交有基础代码，前端vue这块，暂时还没有提交代码。

**Comment by Rashomon511** [comment]
什么时候正式开始，作为前端菜鸟可以贡献代码吗

**Comment by hstarorg** [comment]
@LuoShengMen 欢迎贡献代码，现在的进度是UI原型稿设计阶段。现在前后端都已经有代码，随时可以贡献代码。只是当前的文档不全，有点难以开发功能块。

**Comment by Rashomon511** [comment]
原型我看了下之前的，有时间写下前端代码

**Comment by hstarorg** [comment]
@LuoShengMen 期待参与~

**Comment by hstarorg** [comment]
最近项目技术栈：
frontend: vue2+webpack+weUI+sass(scss)
api: Express(rest-express) +mongoose
admin: ng2(ng2-modular-platform) + AdminLTE+webpack2+gulp

**Comment by hstarorg** [comment]
最新更新:admin: React + antd
