### ISSUE TITLE
成都前端交流群（206731784）招聘信息汇总

### ISSUE THREAD

**Issue by hstarorg** [chengdujs/cd-it-job#3]
本群招聘信息汇总于此，定期更新。如果有招聘信息，可以在群里每周发一次，然后以评论的方式在该issue下更新。感谢支持~

**Comment by IWSR** [comment]
真的会有hr用github吗

**Comment by hstarorg** [comment]
@IWSR 不是针对HR，有小伙伴在群里发招聘信息，这个时候可以搬到这里来。然后给一个链接到群公告~

**Comment by jyhjn1** [comment]
岗位：全栈
公司：中移物联网有限公司成都信息技术中心
地址：天府软件园c区，6月份会搬到天府三街腾讯大厦
工作经验：要求一年半以上
薪资：8K以上具体面谈
福利：公积金按工资12%交，企业年金，补充医疗保险，年终奖，高额电话费等

岗位职责：
1、负责前端架构技术选型、架构设计和具体研发；
2、负责前端项目进度的推进，与团队成员一起解决项目过程中遇到的问题；
3、对项目前端部分的作品负责，有能力确保前端作品符合产品设计的要求；
4、规范前端工作的研发工具、研发文档，带领后入职的前端研发工程师尽快进入角色。

任职要求：
1、深刻理解Web标准，对可用性、可访问性等相关知识有实际的了解和实践经验；
2、精通各种Web前端技术，包括HTML5/DIV+CSS3/XML/Javascript/jQuery等；
3、具备一定的跨浏览器开发经验；代码兼容IE全系列，360，chrome，搜狗，火狐主流浏览器；
4、具备良好的分析问题、解决问题能力，能独立承担任务和有系统进度把控能力；
5、责任心强，具备良好的沟通和团队协作能力，主动、好学；
6、具备一定的平面设计能力者优先。

帮转发的
有意联系QQ：905831689

**Comment by hstarorg** [comment]
@jyhjn1 哈哈，这要求，差不多是中高级前端了~

**Comment by joker1u3** [comment]
@jyhjn1 全栈不要求后端技能么  ～

**Comment by hstarorg** [comment]
@wangjiakun 到了中高级，不懂点后端，说不过去吧。。

**Comment by joker1u3** [comment]
@hstarorg 不好说。。技术钻得深的可能只对后端保持了解，实践上会差一点，比较强的是前端的技术和业务能力。最重要的是如果有要求就明确写出来比较好，需求明确。

**Comment by hstarorg** [comment]
@wangjiakun 确实如此。

**Comment by Frank-C-Zhang** [comment]
这是啥东东项目哦

**Comment by hstarorg** [comment]
@FourLeafClover 一个涉及较多知识点的学习项目。最终有可能作为一个垂直招聘渠道。

**Comment by hstarorg** [comment]
公司：新蛋科技
职位：.NET/C#软件开发实习生
能力要求：
1、具备良好的团队协作能力, 沟通表达能力, 理解能力.
2、具备快速学习能力以及发现问题，解决问题的能力, 严谨的逻辑思维以及喜爱迎接各种挑战.
3、对计算机技术领域充满了较强求知欲和热情, 对业界技术的发展和进步具备良好地敏锐度和学习的欲望.
4、具备一定的计算机基础知识, 比如: 数据结构, 操作系统, 算法, 计算机网络, 数据库系统概论, 高数，线性代数，离散数学.
5、熟悉一种或多种开发语言: C, C++, Java, C#, Objective-C, Python, Ruby, NodeJS, Go.
6、熟悉面向对象开发思想和基本特性. 了解面向对象程序设计的基本原则和设计模式.
7、熟悉一种或多种大型关系型数据库, SQL Server, Oracle, MySql. 具备一定的SQL Script编写能力.
8、本岗位不接受短期实习，只接受实习后会转正并长期发展的简历投递。 
新蛋提供的实习内容：
1、公司为每一位实习生安排导师，并指定详细的实习培养计划；
2、了解企业文化，相关制度规范 ；
3、学习相关专业技能，包括行业业务，技术等；
4、进入团队，参与实际项目，产出实际成果；
5、了解项目实施流程，熟悉团队合作方式；
6、公司可安排给予毕业设计方面的支持和指导；
7、进行实习期考核和出具实习评价鉴定。

**有意，请在群中联系@成都☆幻~精灵**

**Comment by hstarorg** [comment]
公司：新蛋科技
职位：.Net软件开发工程师
岗位职责：
1. 运用 .NET技术平台从事应用软件开发
2. 按照功能需求进行程序设计、编码和测试
任职要求： 
1.    熟练掌握C#、Javascript、HTML、CSS等语言；
2.    熟悉SQL Server数据库，熟练使用T-SQL语言；
3.    较强的发现、分析、解决问题能力
4.    具有良好的英语读写能力

**有意，请在群中联系@成都☆幻~精灵**

**Comment by hstarorg** [comment]
以上已失效。
