### ISSUE TITLE
eventBus？

### ISSUE THREAD

**Issue by yibuyisheng** [chengdujs/cd-it-job#4]
看了下项目引入了 vuex ，为什么还会需要 eventBus 呢？

**Comment by hstarorg** [comment]
两者适用的场景有些许差别，vuex适合存储全局共享的属性，eventBus适合发一起系统级别的事件通知，如登录成功，登出等。

另，多提供一种数据交互方式。

**Comment by yibuyisheng** [comment]
vuex 整个结构其实是为了维护应用的状态，一旦状态发生变化，就会向外部发出通知。登录和登出都是触发 应用状态变化的操作，所以 view 层只需要监听好 vuex 内部的变化，然后根据 store 当前的 state ，对界面做出相应改动就行了，并不需要 eventBus 。如果加入 eventBus ，会极大增加应用的 state 和界面不一致的风险。

**Comment by hstarorg** [comment]
理论上是这样，但有些数据不需要持久化到 `vuex` 的。虽然加了 `eventBus` ，但也只会有限的使用。

**Comment by yibuyisheng** [comment]
比如说，是些什么数据呢？

**Comment by hstarorg** [comment]
一般场景：菜单被点击了，把点击的菜单数据发个事件；
极限场景：兄弟组件之间进行通信（不好的实现方式）

**Comment by mabelyong** [comment]
没这样用过，只在组件内部使用过，这样全局抽出来是为了使用更方便吗？

**Comment by hstarorg** [comment]
@mabelyong 算是多一种交互方式吧，vuex如果太庞大，也不太好维护。所以只需要通知状态变更，必须要存储数据，就可以用这种了。

**Comment by yelingfeng** [comment]
没vuex 怎么愉快的玩耍 - -

**Comment by hstarorg** [comment]
@yelingfeng 集成了Vuex的。

**Comment by hstarorg** [comment]
讨论完毕~
